name: Manual PR Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Create PR
      run: |
        git checkout staging

        # Create a pull request to main-gk branch
        gh pr create --base main-gk --head staging --title "Release ${{ github.event.inputs.version }}" --body "Release version ${{ github.event.inputs.version }}"
      env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

