name: Manual PR Deployment to main

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1


    - name: Create PR
      run: |
        git checkout staging

        # Create a pull request to main-gk branch
        gh pr create --base main-gk --head staging --title "Release-${{ github.event.inputs.version }}" --body "Release version ${{ github.event.inputs.version }}"
      env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Merge PR info
      id: tag_info_out
      run: |
        merged_commit_sha=$(git rev-parse "HEAD^{commit}")
        pr_title=$(git log --merges --pretty=format:"%b" -n 1 $merged_commit_sha | grep -oP "(?<=Merge pull request #\d+ from .*:\s).*" | tr -d '\n')
        echo "PR title: $pr_title"
        # Optionally, you can format the PR title if needed (e.g., removing spaces)
        formatted_pr_title=$(echo "$pr_title" | tr -d ' ')
        echo"Formatted PR title: $formatted_pr_title"
        echo "::set-output name=TAG_INFO::${formatted_pr_title}"